# Generated by Django 5.0.2 on 2024-03-04 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="user",
        ),
        migrations.AddField(
            model_name="author",
            name="password",
            field=models.CharField(default="password123", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="author",
            name="username",
            field=models.CharField(default="password123", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="NewsStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=64)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pol", "Politics"),
                            ("art", "Art"),
                            ("tech", "Technology"),
                            ("trivia", "Trivia"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[("uk", "UK"), ("eu", "Europe"), ("w", "World")],
                        max_length=10,
                    ),
                ),
                ("date", models.DateField()),
                ("details", models.CharField(max_length=128)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news_api.author",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Story",
        ),
    ]
